### PR TITLE
Tests for PlayerDao, dependency cleanup, fixed delete() implementation in TeamDaoImpl

### LINKED ISSUE #14: Create tests for entity class Player

### PR DESCRIPTION
**Pull request by kaprijela**

### CODE REVIEW

File: src/test/java/cz/fi/muni/pa165/esports/dao/PlayerDaoTest.java [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+        Player foundPlayer = em.find(Player.class, mrWhite.getPlayer_id());
+
+        Assert.assertNotNull(foundPlayer);
+        Assert.assertEquals(mrWhite, foundPlayer);
+        Assert.assertEquals(foundPlayer.getName(), mrWhite.getName());
+        Assert.assertEquals(foundPlayer.getAge(), mrWhite.getAge());
+        Assert.assertEquals(foundPlayer.getGender(), mrWhite.getGender());
+    }
+
+    @Test(expectedExceptions = { PersistenceException.class })
```
Comment (kaprijela) [inline src/test/java/cz/fi/muni/pa165/esports/dao/PlayerDaoTest.java:97]: I'm not sure if this is the right exception, but it's the one that gets thrown so... (It also depends on the configuration, there is a bean that translates exceptions)

File: src/test/java/cz/fi/muni/pa165/esports/dao/PlayerDaoTest.java [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+        for (Player player: players) {
+            if (player.getName().equals(expectedPlayerName)) {
+                return;
+            }
+        }
+        Assert.fail("Couldn't find player " + expectedPlayerName + " in collection " + players);
+    }
+
+    @AfterClass
+    private void cleanUp() {
```
Comment (sithcom255) [inline src/test/java/cz/fi/muni/pa165/esports/dao/PlayerDaoTest.java:194]: is this needed?

Comment (kaprijela) [reply src/test/java/cz/fi/muni/pa165/esports/dao/PlayerDaoTest.java:194]: the `cleanUp()` method? I create an entity manager manually in my tests, so I wanted to make sure and close it manually as well, but I'm not sure to be honest.

**Review by RadovanTomik — APPROVED** [review]
